-- Script de ingestão para tabela workspace.postech_tech_challenge_f3.flights

-- Criação da tabela caso não exista
CREATE TABLE IF NOT EXISTS workspace.postech_tech_challenge_f3.flights (
    YEAR BIGINT,
    MONTH BIGINT,
    DAY BIGINT,
    DAY_OF_WEEK BIGINT,
    AIRLINE STRING,
    FLIGHT_NUMBER BIGINT,
    TAIL_NUMBER STRING,
    ORIGIN_AIRPORT STRING,
    DESTINATION_AIRPORT STRING,
    SCHEDULED_DEPARTURE BIGINT,
    DEPARTURE_TIME BIGINT,
    DEPARTURE_DELAY BIGINT,
    SCHEDULED_ARRIVAL BIGINT,
    ARRIVAL_TIME BIGINT,
    ARRIVAL_DELAY BIGINT,
    AIR_TIME BIGINT,
    DISTANCE BIGINT,
    WHEELS_ON BIGINT,
    TAXI_IN BIGINT,
    TAXI_OUT BIGINT,
    CANCELLED BIGINT,
    CANCELLATION_REASON STRING,
    DIVERTED BIGINT,
    SCHEDULED_TIME BIGINT,
    ELAPSED_TIME BIGINT
);

-- Limpar tabela antes de executar nova ingestão
DELETE FROM workspace.postech_tech_challenge_f3.flights;

-- Ingestão via COPY INTO mapeando todas as colunas
COPY INTO workspace.postech_tech_challenge_f3.flights
FROM (SELECT
    CAST(YEAR AS BIGINT) AS YEAR,
    CAST(MONTH AS BIGINT) AS MONTH,
    CAST(DAY AS BIGINT) AS DAY,
    CAST(DAY_OF_WEEK AS BIGINT) AS DAY_OF_WEEK,
    AIRLINE,
    CAST(FLIGHT_NUMBER AS BIGINT) AS FLIGHT_NUMBER,
    TAIL_NUMBER,
    ORIGIN_AIRPORT,
    DESTINATION_AIRPORT,
    CAST(SCHEDULED_DEPARTURE AS BIGINT) AS SCHEDULED_DEPARTURE,
    CAST(DEPARTURE_TIME AS BIGINT) AS DEPARTURE_TIME,
    CAST(DEPARTURE_DELAY AS BIGINT) AS DEPARTURE_DELAY,
    CAST(SCHEDULED_ARRIVAL AS BIGINT) AS SCHEDULED_ARRIVAL,
    CAST(ARRIVAL_TIME AS BIGINT) AS ARRIVAL_TIME,
    CAST(ARRIVAL_DELAY AS BIGINT) AS ARRIVAL_DELAY,
    CAST(AIR_TIME AS BIGINT) AS AIR_TIME,
    CAST(DISTANCE AS BIGINT) AS DISTANCE,
    CAST(WHEELS_ON AS BIGINT) AS WHEELS_ON,
    CAST(TAXI_IN AS BIGINT) AS TAXI_IN,
    CAST(TAXI_OUT AS BIGINT) AS TAXI_OUT,
    CAST(CANCELLED AS BIGINT) AS CANCELLED,
    CANCELLATION_REASON,
    CAST(DIVERTED AS BIGINT) AS DIVERTED,
    CAST(SCHEDULED_TIME AS BIGINT) AS SCHEDULED_TIME,
    CAST(ELAPSED_TIME AS BIGINT) AS ELAPSED_TIME
FROM '/Volumes/workspace/postech_tech_challenge_f3/raw/2026-03-09/flights.csv')
FILEFORMAT = CSV
FORMAT_OPTIONS ('header' = 'true');
